services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: "sqlite"
    volumes:
      - ./data:/data
  redis:
    image: "redis:alpine"
  sqlite:
    image: "nouchka/sqlite3"
    volumes:
      - ./data:/root/db
    command: sqlite3 /root/db/simulation.db
